dataset_root: "/data/lungcancer"
num_classes: 3   # LC25000 lung subset: {normal, adenocarcinoma, squamous}
img_size: 384
batch_size: 32
epochs: 12
lr: 3e-4
weights: "resnet18"
augment: true
label_smoothing: 0.05
export_path: "../backend/models/lungcancer_resnet18.pt"
